Repository utilForever/RosettaStone, pull requests merged in 2018-08, with the labels that each got.

#109 Implement basic abilities - Poisonous, Divine Shield, Taunt, Stealth, Windfury, Freeze (#73, #74, #102)
  Includes/Cards/Character.h
  Includes/Enchants/Effects.h
  Includes/Enums/TaskEnums.h
  Includes/Managers/Player.h
  Includes/Tasks/BasicTasks/InitAttackCountTask.h
  Includes/Tasks/MetaData.h
  Includes/Tasks/PowerTasks/FreezeTask.h
  Includes/Tasks/PowerTasks/PoisonousTask.h
  Sources/Managers/GameAgent.cpp
  Sources/Tasks/BasicTasks/CombatTask.cpp
  Sources/Tasks/BasicTasks/InitAttackCountTask.cpp
  Sources/Tasks/BasicTasks/ModifyHealthTask.cpp
  Sources/Tasks/BasicTasks/PlayMinionTask.cpp
  Sources/Tasks/BasicTasks/SwapPlayerTask.cpp
  Sources/Tasks/PowerTasks/FreezeTask.cpp
  Sources/Tasks/PowerTasks/PoisonousTask.cpp
  Sources/Tasks/TaskSerializer.cpp
  Tests/UnitTests/CardSets/BasicCardTests.cpp
Labels: Improvement, New Feature, Review

#114 Implement Magma Rager (CS2_118) (#73)
  Sources/CardSets/BasicCardsGen.cpp
  Tests/UnitTests/CardSets/BasicCardTests.cpp
Labels: New Feature, Review

#111 Implement Succubus (EX1_306) (#73)
  Includes/Enums/TaskEnums.h
  Includes/Tasks/MetaData.h
  Includes/Tasks/PowerTasks/DiscardTask.h
  Sources/CardSets/BasicCardsGen.cpp
  Sources/Tasks/PowerTasks/DiscardTask.cpp
  Tests/UnitTests/CardSets/BasicCardTests.cpp
Labels: New Feature, Review

#115 Implement King Krush, Wolfrider, Reckless Rocketeer, Stormwind Knight, Bluegill Warrior (EX1_543, CS2_124, CS2_213, CS2_131, CS2_173) (#73)
  Sources/CardSets/BasicCardsGen.cpp
  Tests/UnitTests/CardSets/BasicCardTests.cpp
Labels: New Feature, Review

#116 Implement Core Hound (CS2_201) and add 'spellDamage' field (#73)
  Includes/Cards/Card.h
  Includes/Cards/Cards.h
  Sources/CardSets/BasicCardsGen.cpp
  Sources/Cards/Cards.cpp
  Sources/Loaders/CardLoader.cpp
  Tests/UnitTests/CardSets/BasicCardTests.cpp
  Tests/UnitTests/Cards/CardsTests.cpp
Labels: New Feature, Review

#117 Refactor console program (#46)
  Datas/test1.json
  Datas/test2.json
  Includes/Flatbuffers/generated/FlatData_generated.h
  Includes/Flatbuffers/schema/FlatData.fbs
  Includes/Managers/GameInterface.h
  Includes/Tasks/MetaData.h
  Includes/Tasks/TaskAgent.h
  Includes/Tasks/TaskMeta.h
  Includes/Tasks/TaskSerializer.h
  Sources/Managers/GameAgent.cpp
  Sources/Managers/GameInterface.cpp
  Sources/Tasks/BasicTasks/CombatTask.cpp
  Sources/Tasks/BasicTasks/DrawTask.cpp
  Sources/Tasks/BasicTasks/ModifyHealthTask.cpp
  Sources/Tasks/BasicTasks/PlayMinionTask.cpp
  Sources/Tasks/BasicTasks/PlayerSettingTask.cpp
  Sources/Tasks/BasicTasks/Wrapper.cpp
  Sources/Tasks/TaskAgent.cpp
  Sources/Tasks/TaskMeta.cpp
  Sources/Tasks/TaskSerializer.cpp
  Tests/UnitTests/Tasks/TaskAgentTests.cpp
Labels: Bug, Improvement, Review

#118 Add 'COMBAT_TARGET_IMMUNE' enum (#73)
  Includes/Tasks/MetaData.h
  Sources/Tasks/BasicTasks/CombatTask.cpp
Labels: New Feature, Review

#120 Add TaskSerializer test (#75)
  Sources/Tasks/BasicTasks/CombatTask.cpp
  Sources/Tasks/TaskSerializer.cpp
  Tests/UnitTests/Tasks/TaskSerializerTests.cpp
  Tests/UnitTests/Utils/TestUtils.cpp
  Tests/UnitTests/Utils/TestUtils.h
Labels: Improvement, Review

#122 Implement Guardian of Kings and HealTask (CS2_088) (#73)
  Includes/Enums/TaskEnums.h
  Includes/Tasks/MetaData.h
  Includes/Tasks/PowerTasks/HealTask.h
  Sources/CardSets/BasicCardsGen.cpp
  Sources/Tasks/PowerTasks/HealTask.cpp
  Sources/gtest.pc
  Sources/gtest_main.pc
  Tests/UnitTests/CardSets/BasicCardTests.cpp
Labels: New Feature, Review

#123 Implement Booty Bay Bodyguard (CS2_187)
  Sources/CardSets/BasicCardsGen.cpp
  Tests/UnitTests/CardSets/BasicCardTests.cpp
Labels: New Feature, Review

#127 Separate whole basic card test file by card (#125)
  .gitignore
  README.md
  Tests/UnitTests/CardSets/Basic/EX1_008.cpp
  Tests/UnitTests/CardSets/Basic/EX1_017.cpp
  Tests/UnitTests/CardSets/Basic/EX1_066.cpp
  Tests/UnitTests/CardSets/Basic/EX1_170.cpp
  Tests/UnitTests/CardSets/Basic/EX1_306.cpp
  Tests/UnitTests/CardSets/Basic/EX1_543.cpp
  Tests/UnitTests/CardSets/BasicCardTests.cpp
  Tests/UnitTests/CardSets/Classic/CS2_041.cpp
  Tests/UnitTests/CardSets/Classic/CS2_088.cpp
  Tests/UnitTests/CardSets/Classic/CS2_118.cpp
  Tests/UnitTests/CardSets/Classic/CS2_124.cpp
  Tests/UnitTests/CardSets/Classic/CS2_125.cpp
  Tests/UnitTests/CardSets/Classic/CS2_131.cpp
  Tests/UnitTests/CardSets/Classic/CS2_169.cpp
  Tests/UnitTests/CardSets/Classic/CS2_171.cpp
  Tests/UnitTests/CardSets/Classic/CS2_172.cpp
  Tests/UnitTests/CardSets/Classic/CS2_179.cpp
  Tests/UnitTests/CardSets/Classic/CS2_182.cpp
  Tests/UnitTests/CardSets/Classic/CS2_187.cpp
  Tests/UnitTests/CardSets/Classic/CS2_201.cpp
  Tests/UnitTests/CardSets/Classic/CS2_213.cpp
  Tests/UnitTests/Tasks/TaskMetaTests.cpp
  Tests/UnitTests/Tasks/TaskSerializerTests.cpp
  Tests/UnitTests/UnitTests.cpp
  Tests/UnitTests/Utils/CardSetUtils.h
Labels: Improvement, Review

#130 Move DestoryTask from PowerTask to BasicTask (#131)
  Includes/Enums/TaskEnums.h
  Includes/Tasks/BasicTasks/DestroyMinionTask.h
  Includes/Tasks/BasicTasks/DestroyTask.h
  Includes/Tasks/BasicTasks/DestroyWeaponTask.h
  Includes/Tasks/MetaData.h
  Sources/CardSets/BasicCardsGen.cpp
  Sources/Tasks/BasicTasks/CombatTask.cpp
  Sources/Tasks/BasicTasks/DestroyMinionTask.cpp
  Sources/Tasks/BasicTasks/DestroyTask.cpp
  Sources/Tasks/BasicTasks/DestroyWeaponTask.cpp
  Sources/Tasks/PowerTasks/DestroyTask.cpp
Labels: Improvement, Review

#134 Make utility tools for convenience (#119)
  CMakeLists.txt
  Includes/Cards/Cards.h
  Includes/Enums/CardEnums.h
  Sources/Cards/Cards.cpp
  Tests/UnitTests/Cards/CardsTests.cpp
  Tools/CMakeLists.txt
  Tools/main.cpp
  codecov.yml
Labels: New Feature, Review

#136 Fix bug of TaskAgentTests assertion failure and implement some BasicTasks tests (#75, #129)
  Includes/Tasks/BasicTasks/DrawTask.h
  Includes/Tasks/BasicTasks/InitAttackCountTask.h
  Sources/Tasks/BasicTasks/DrawTask.cpp
  Sources/Tasks/BasicTasks/InitAttackCountTask.cpp
  Sources/Tasks/BasicTasks/SwapPlayerTask.cpp
  Tests/UnitTests/CardSets/Basic/EX1_008.cpp
  Tests/UnitTests/CardSets/Basic/EX1_017.cpp
  Tests/UnitTests/CardSets/Classic/CS2_125.cpp
  Tests/UnitTests/CardSets/Classic/CS2_169.cpp
  Tests/UnitTests/Tasks/BasicTasks/BriefTaskTests.cpp
  Tests/UnitTests/Tasks/BasicTasks/CombatTaskTests.cpp
  Tests/UnitTests/Tasks/BasicTasks/DrawTaskTests.cpp
  Tests/UnitTests/Tasks/BasicTasks/GameEndTaskTests.cpp
  Tests/UnitTests/Tasks/BasicTasks/InitAttackCountTaskTests.cpp
  Tests/UnitTests/Tasks/TaskAgentTests.cpp
  Tests/UnitTests/Utils/TestUtils.cpp
  Tests/UnitTests/Utils/TestUtils.h
Labels: Bug, Improvement, Review

#139 Add LGTM.com C/C++ analysis configuration and badges (#138)
  .lgtm.yml
  README.md
Labels: New Feature, Review
