Repository utilForever/RosettaStone, pull requests merged in 2020-11, with the labels that each got.

#530 Implement 20 ULDUM cards and rework health related variables and methods
  Documents/CardList.md
  Extensions/RosettaRL/Includes/NeuralNet/FieldEnums.hpp
  Extensions/RosettaRL/Sources/Judges/JSON/Reader.cpp
  Extensions/RosettaRL/Sources/NeuralNet/GameDataBridge.cpp
  Extensions/RosettaRL/Sources/NeuralNet/libtorch/InputDataConverter.cpp
  Extensions/RosettaRL/Sources/NeuralNet/tiny-dnn/InputDataConverter.cpp
  Includes/Rosetta/Common/Enums/ChoiceEnums.hpp
  Includes/Rosetta/PlayMode/Conditions/SelfCondition.hpp
  Includes/Rosetta/PlayMode/Enchants/Attrs/Health.hpp
  Includes/Rosetta/PlayMode/Enchants/Effects.hpp
  Includes/Rosetta/PlayMode/Models/Character.hpp
  Includes/Rosetta/PlayMode/Views/Types/Player.hpp
  README.md
  Sources/Rosetta/PlayMode/Actions/PlayCard.cpp
  Sources/Rosetta/PlayMode/CardSets/BlackTempleCardsGen.cpp
  Sources/Rosetta/PlayMode/CardSets/DalaranCardsGen.cpp
  Sources/Rosetta/PlayMode/CardSets/DragonsCardsGen.cpp
  Sources/Rosetta/PlayMode/CardSets/Expert1CardsGen.cpp
  Sources/Rosetta/PlayMode/CardSets/UldumCardsGen.cpp
  Sources/Rosetta/PlayMode/Conditions/SelfCondition.cpp
  Sources/Rosetta/PlayMode/Enchants/Enchants.cpp
  Sources/Rosetta/PlayMode/Games/GameRestorer.cpp
  Sources/Rosetta/PlayMode/Models/Character.cpp
  Sources/Rosetta/PlayMode/Models/Minion.cpp
  Sources/Rosetta/PlayMode/Tasks/SimpleTasks/DiscoverTask.cpp
  Sources/Rosetta/PlayMode/Utils/JSONSerializer.cpp
  Sources/Rosetta/PlayMode/Views/Types/Player.cpp
  Tests/UnitTests/PlayMode/CardSets/BlackTempleCardsGenTests.cpp
  Tests/UnitTests/PlayMode/CardSets/Expert1CardsGenTests.cpp
  Tests/UnitTests/PlayMode/CardSets/UldumCardsGenTests.cpp
  Tests/UnitTests/PlayMode/Models/CharacterTests.cpp
Labels: size/XXL

#532 Update Hearthstone Patch 18.6.1
  Includes/Rosetta/Common/Constants.hpp
  Resources/cards.collectible.json
  Resources/cards.json
  Sources/Rosetta/Battlegrounds/Models/MinionPool.cpp
  Tests/UnitTests/Battlegrounds/CardSets/BattlegroundsCardsGenTests.cpp
Labels: size/L

#533 Implement 10 YEAR_OF_THE_DRAGON cards
  Documents/CardList.md
  Includes/Rosetta/PlayMode/Conditions/SelfCondition.hpp
  README.md
  Sources/Rosetta/PlayMode/CardSets/ScholomanceCardsGen.cpp
  Sources/Rosetta/PlayMode/CardSets/YoDCardsGen.cpp
  Sources/Rosetta/PlayMode/Conditions/SelfCondition.cpp
  Sources/Rosetta/PlayMode/Models/Playable.cpp
  Sources/Rosetta/PlayMode/Tasks/SimpleTasks/TransformMinionTask.cpp
  Tests/UnitTests/PlayMode/CardSets/ScholomanceCardsGenTests.cpp
  Tests/UnitTests/PlayMode/CardSets/YoDCardsGenTests.cpp
Labels: size/XL

#535 Implement 10 SCHOLOMANCE cards
  Documents/CardList.md
  Includes/Rosetta/Common/Enums/ChoiceEnums.hpp
  Includes/Rosetta/PlayMode/Conditions/SelfCondition.hpp
  README.md
  Sources/Rosetta/PlayMode/CardSets/DalaranCardsGen.cpp
  Sources/Rosetta/PlayMode/CardSets/ScholomanceCardsGen.cpp
  Sources/Rosetta/PlayMode/Conditions/SelfCondition.cpp
  Sources/Rosetta/PlayMode/Loaders/CardLoader.cpp
  Sources/Rosetta/PlayMode/Tasks/SimpleTasks/DiscoverTask.cpp
  Sources/Rosetta/PlayMode/Zones/HandZone.cpp
  Tests/UnitTests/PlayMode/CardSets/DalaranCardsGenTests.cpp
  Tests/UnitTests/PlayMode/CardSets/Expert1CardsGenTests.cpp
  Tests/UnitTests/PlayMode/CardSets/ScholomanceCardsGenTests.cpp
Labels: size/XXL

#537 Implement 18 DARKMOON_FAIRE cards and keyword 'Corrupt'
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  .github/workflows/ubuntu_codecov.yml
  .github/workflows/windows.yml
  Documents/AbilityList.md
  Documents/CardList.md
  Includes/Rosetta/PlayMode/Cards/CardDef.hpp
  Includes/Rosetta/PlayMode/Models/Playable.hpp
  README.md
  Scripts/card_comment_gen.py
  Sources/Rosetta/PlayMode/Actions/Generic.cpp
  Sources/Rosetta/PlayMode/Actions/PlayCard.cpp
  Sources/Rosetta/PlayMode/CardSets/DarkmoonFaireCardsGen.cpp
  Sources/Rosetta/PlayMode/Cards/CardDef.cpp
  Sources/Rosetta/PlayMode/Loaders/CardLoader.cpp
  Sources/Rosetta/PlayMode/Loaders/InternalCardLoader.cpp
  Sources/Rosetta/PlayMode/Models/Playable.cpp
  Tests/UnitTests/PlayMode/CardSets/BlackTempleCardsGenTests.cpp
  Tests/UnitTests/PlayMode/CardSets/DarkmoonFaireCardsGenTests.cpp
Labels: size/XXL

#539 Implement 2 SCHOLOMANCE cards
  .github/workflows/ubuntu.yml
  Documents/CardList.md
  Documents/PullRequests.md
  Includes/Rosetta/Common/Enums/ChoiceEnums.hpp
  Includes/Rosetta/PlayMode/Tasks/SimpleTasks/DiscoverTask.hpp
  Includes/Rosetta/PlayMode/Zones/DeckZone.hpp
  Sources/Rosetta/PlayMode/CardSets/ScholomanceCardsGen.cpp
  Sources/Rosetta/PlayMode/Tasks/SimpleTasks/DiscoverTask.cpp
  Sources/Rosetta/PlayMode/Zones/DeckZone.cpp
  Tests/UnitTests/PlayMode/CardSets/ScholomanceCardsGenTests.cpp
Labels: size/L

#540 Implement 15 ULDUM cards
  Documents/CardList.md
  Includes/Rosetta/Common/Enums/CardEnums.hpp
  Includes/Rosetta/Common/Enums/ChoiceEnums.hpp
  Includes/Rosetta/Common/Enums/PlayReqCustom.def
  Includes/Rosetta/PlayMode/Loaders/TargetingPredicates.hpp
  Includes/Rosetta/PlayMode/Tasks/SimpleTasks/TransformMinionTask.hpp
  README.md
  Sources/Rosetta/PlayMode/Actions/Choose.cpp
  Sources/Rosetta/PlayMode/Auras/Aura.cpp
  Sources/Rosetta/PlayMode/CardSets/CoreCardsGen.cpp
  Sources/Rosetta/PlayMode/CardSets/HoFCardsGen.cpp
  Sources/Rosetta/PlayMode/CardSets/UldumCardsGen.cpp
  Sources/Rosetta/PlayMode/Cards/Card.cpp
  Sources/Rosetta/PlayMode/Loaders/TargetingPredicates.cpp
  Sources/Rosetta/PlayMode/Models/Character.cpp
  Sources/Rosetta/PlayMode/Models/Choice.cpp
  Sources/Rosetta/PlayMode/Tasks/SimpleTasks/DiscoverTask.cpp
  Sources/Rosetta/PlayMode/Tasks/SimpleTasks/TransformMinionTask.cpp
  Tests/UnitTests/PlayMode/CardSets/UldumCardsGenTests.cpp
Labels: size/XXL
