Repository utilForever/RosettaStone, pull requests merged in 2021-01, with the labels that each got.

#551 Implement 2 SCHOLOMANCE cards
  Documents/CardList.md
  README.md
  Sources/Rosetta/PlayMode/CardSets/ScholomanceCardsGen.cpp
  Tests/UnitTests/PlayMode/CardSets/ScholomanceCardsGenTests.cpp
Labels: size/L

#553 Implement 21 ULDUM cards
  Documents/CardList.md
  Documents/TaskList.md
  Includes/Rosetta/Common/Enums/ChoiceEnums.hpp
  Includes/Rosetta/PlayMode/CardSets/TgtCardsGen.hpp
  Includes/Rosetta/PlayMode/Cards/Cards.hpp
  Includes/Rosetta/PlayMode/Conditions/SelfCondition.hpp
  Includes/Rosetta/PlayMode/Models/Playable.hpp
  Includes/Rosetta/PlayMode/Tasks/SimpleTasks/ConsecutiveDamageTask.hpp
  Includes/Rosetta/PlayMode/Tasks/SimpleTasks/DiscardTask.hpp
  Includes/Rosetta/PlayMode/Tasks/SimpleTasks/QuestProgressTask.hpp
  Includes/Rosetta/PlayMode/Tasks/SimpleTasks/SwapTopCardTask.hpp
  Includes/Rosetta/RosettaStone.hpp
  README.md
  Sources/Rosetta/PlayMode/Actions/Choose.cpp
  Sources/Rosetta/PlayMode/CardSets/CoreCardsGen.cpp
  Sources/Rosetta/PlayMode/CardSets/HoFCardsGen.cpp
  Sources/Rosetta/PlayMode/CardSets/TgtCardsGen.cpp
  Sources/Rosetta/PlayMode/CardSets/UldumCardsGen.cpp
  Sources/Rosetta/PlayMode/Cards/CardDefs.cpp
  Sources/Rosetta/PlayMode/Cards/Cards.cpp
  Sources/Rosetta/PlayMode/Conditions/SelfCondition.cpp
  Sources/Rosetta/PlayMode/Loaders/CardLoader.cpp
  Sources/Rosetta/PlayMode/Models/Character.cpp
  Sources/Rosetta/PlayMode/Models/Playable.cpp
  Sources/Rosetta/PlayMode/Tasks/PlayerTasks/HeroPowerTask.cpp
  Sources/Rosetta/PlayMode/Tasks/SimpleTasks/ConsecutiveDamageTask.cpp
  Sources/Rosetta/PlayMode/Tasks/SimpleTasks/CopyTask.cpp
  Sources/Rosetta/PlayMode/Tasks/SimpleTasks/DamageTask.cpp
  Sources/Rosetta/PlayMode/Tasks/SimpleTasks/DiscardTask.cpp
  Sources/Rosetta/PlayMode/Tasks/SimpleTasks/DiscoverTask.cpp
  Sources/Rosetta/PlayMode/Tasks/SimpleTasks/QuestProgressTask.cpp
  Sources/Rosetta/PlayMode/Tasks/SimpleTasks/SwapTopCardTask.cpp
  Tests/UnitTests/PlayMode/CardSets/UldumCardsGenTests.cpp
  Tests/UnitTests/PlayMode/Models/CharacterTests.cpp
Labels: size/XXL

#554 Update Hearthstone Patch 19.2.1
  Resources/cards.collectible.json
  Resources/cards.json
  Sources/Rosetta/PlayMode/CardSets/Expert1CardsGen.cpp
  Tests/UnitTests/PlayMode/CardSets/Expert1CardsGenTests.cpp
Labels: size/S

#557 Implement 13 SCHOLOMANCE cards
  Documents/CardList.md
  Includes/Rosetta/Common/Enums/AuraEnums.hpp
  Includes/Rosetta/Common/Enums/TriggerEnums.hpp
  Includes/Rosetta/PlayMode/Conditions/SelfCondition.hpp
  Includes/Rosetta/PlayMode/Enchants/AuraEffects.hpp
  Includes/Rosetta/PlayMode/Managers/TriggerManager.hpp
  Includes/Rosetta/PlayMode/Models/Entity.hpp
  Includes/Rosetta/PlayMode/Models/Hero.hpp
  README.md
  Sources/Rosetta/PlayMode/Auras/Aura.cpp
  Sources/Rosetta/PlayMode/CardSets/ScholomanceCardsGen.cpp
  Sources/Rosetta/PlayMode/Conditions/SelfCondition.cpp
  Sources/Rosetta/PlayMode/Enchants/AuraEffects.cpp
  Sources/Rosetta/PlayMode/Enchants/Effect.cpp
  Sources/Rosetta/PlayMode/Managers/TriggerManager.cpp
  Sources/Rosetta/PlayMode/Models/Entity.cpp
  Sources/Rosetta/PlayMode/Models/Hero.cpp
  Sources/Rosetta/PlayMode/Tasks/SimpleTasks/DiscardTask.cpp
  Sources/Rosetta/PlayMode/Triggers/Trigger.cpp
  Tests/UnitTests/PlayMode/CardSets/CoreCardsGenTests.cpp
  Tests/UnitTests/PlayMode/CardSets/ScholomanceCardsGenTests.cpp
Labels: size/XXL

#559 Update Hearthstone Patch 19.4.1
  Resources/cards.collectible.json
  Resources/cards.json
  Sources/Rosetta/PlayMode/CardSets/DarkmoonFaireCardsGen.cpp
Labels: size/S

#561 Fix unit test failure of card 'King Phaoris' (ULD_304)
  Tests/UnitTests/PlayMode/CardSets/UldumCardsGenTests.cpp
Labels: size/XS

#562 Correct the logic of keyword 'Dormant'
  Includes/Rosetta/PlayMode/Conditions/SelfCondition.hpp
  Includes/Rosetta/PlayMode/Models/Playable.hpp
  Includes/Rosetta/PlayMode/Tasks/ComplexTask.hpp
  Sources/Rosetta/PlayMode/Actions/PlayCard.cpp
  Sources/Rosetta/PlayMode/Actions/Summon.cpp
  Sources/Rosetta/PlayMode/CardSets/BlackTempleCardsGen.cpp
  Sources/Rosetta/PlayMode/Conditions/SelfCondition.cpp
  Sources/Rosetta/PlayMode/Loaders/CardLoader.cpp
  Sources/Rosetta/PlayMode/Models/Playable.cpp
  Tests/UnitTests/PlayMode/CardSets/BlackTempleCardsGenTests.cpp
Labels: size/L
